From golang:1.22-alpine As builder 

WORKDIR /app

COPY go,mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/pooler ./main.go


# 
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/pooler .
CMD ["./pooler"]
