version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - websocket-net
  pooler:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - websocket-net

  backend:
    build:
      context: ../backend
    depends_on:
      - redis
    networks:
      - websocket-net

networks:
  websocket-net:
    driver: bridge